version: "3.8"
services:
  api-server:
    build: { context: ".", dockerfile: apps/api-server/Dockerfile }
    ports: [ "4000:4000" ]
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    depends_on: [ db ]
  web-client:
    build: { context: ".", dockerfile: apps/web-client/Dockerfile }
    ports: [ "3000:80" ]
    depends_on: [ api-server ]
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes: [ "postgres_data:/var/lib/postgresql/data" ]
volumes:
  postgres_data:
